#!/usr/bin/env bash
# duplicate web-01 to web-02
# these scripts are an upgrade from the web-server scripts...

# uncomment to see the script run in action
#set -x

echo -e "Starting server setup...\n"

function install() {
    command -v "$1" &> /dev/null

    #shellcheck disable=SC2181
    if [ $? -ne 0 ]; then
        echo -e "    Installing: $1...\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    $1 is already installed.\n"
    fi
}

install nginx # install nginx

echo -e "\nSetting up server configurations...\n"

# Allow Nginx through firewall
sudo ufw allow 'Nginx HTTP' > /dev/null

# Grant user permissions to website files
if [ -d "/var/www" ]; then
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
else
    sudo mkdir -p /var/www
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
fi

# Create necessary directories
for dir in /var/www/{html,error}; do
    if ! [ -d "$dir" ]; then
        mkdir -p "$dir"
    fi
done

# Create default index and error page
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Backup default server config if it exists
if [ -f "/etc/nginx/sites-available/default" ]; then
    sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.backup
fi

# Define Nginx server configuration
server_config="server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        add_header X-Served-By \$hostname;
        location / {
            try_files \$uri \$uri/ =404;
        }
        if (\$request_filename ~ redirect_me){
            rewrite ^ https://th3-gr00t.tk/ permanent;
        }
        error_page 404 /error_404.html;
        location = /error_404.html {
            internal;
        }
}"

# Apply Nginx server configuration
echo -e "Applying server configuration...\n"
echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-available/default

# Enable the default server configuration if not already enabled
if [ ! -f "/etc/nginx/sites-enabled/default" ]; then
    sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
fi

# Restart Nginx service
if [ "$(pgrep -c nginx)" -le 0 ]; then
    sudo service nginx start
else
    sudo service nginx restart
fi

echo -e "\nServer setup completed successfully."
