#!/usr/bin/env bash
# 101-Manage process

SCRIPT_PATH="$( cd "$(dirname "$0")" || exit ; pwd -P )"
PROCESS_NAME="manage_my_process"
PID_FILE="/var/run/my_process.pid"

start_process() {
    if [ -f "$PID_FILE" ]; then
        echo "$PROCESS_NAME is already running. PID: $(cat $PID_FILE)"
        exit 1
    fi

    "$SCRIPT_PATH"/manage_my_process &
    echo $! > $PID_FILE
    echo "$PROCESS_NAME started"
}

stop_process() {
    if [ -f "$PID_FILE" ]; then
        kill -9 "$(cat $PID_FILE)"
        rm -f $PID_FILE
        echo "$PROCESS_NAME stopped"
    else
        echo "$PROCESS_NAME is not running"
        exit 1
    fi
}

restart_process() {
    stop_process
    start_process
    echo "$PROCESS_NAME restarted"
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

